const STORAGE_KEY = 'house-die-league-v1';
const FORMAT = 'house-die-week-v1';
const COLORS = ['#00a3e0','#fed141','#061f33','#5bc2e7','#c69214','#325d79'];
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc = (value = '') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today = () => new Date().toISOString().slice(0, 10);
const fmtDate = value => value ? new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : '—';
const normalize = value => String(value || '').trim().toLowerCase();

function initialState(){
  return {version:1,league:{id:uid(),name:'Sigma Chi Die League'},players:[],teams:[],weeks:[{id:uid(),number:1,name:'Week 1',startDate:today(),endDate:''}],series:[],games:[],activeGameId:null,settings:{refereeName:''}};
}
let state = load();
let route = 'home';
let statsTab = 'teams';
let selectedWeek = 'all';
let setup = null;

function load(){
  try { return normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)) || initialState()); }
  catch { return initialState(); }
}
function normalizeState(data){
  data.players=Array.isArray(data.players)?data.players:[];
  data.series=Array.isArray(data.series)?data.series:[];
  data.teams=(data.teams||[]).map(t=>({...t,players:(t.players||[]).map(p=>{let existing=data.players.find(x=>x.id===p.id)||data.players.find(x=>normalize(x.name)===normalize(p.name));if(!existing){existing={id:p.id||uid(),name:p.name};data.players.push(existing);}return{id:existing.id,name:existing.name};})}));
  return data;
}
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function activeTeams(){ return state.teams.filter(t => t.active !== false); }
function currentWeek(){ return state.weeks[state.weeks.length - 1]; }
function team(id){ return state.teams.find(t => t.id === id); }
function game(id){ return state.games.find(g => g.id === id); }
function activeGame(){ return game(state.activeGameId); }
function toast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2600); }
function setRoute(next){ route=next; if(next!=='newGame')setup=null; render(); window.scrollTo({top:0,behavior:'smooth'}); }

function render(){
  $$('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));
  const views={home:renderHome,teams:renderTeams,newGame:renderNewGame,game:renderGame,stats:renderStats,data:renderData};
  $('#app').innerHTML=(views[route]||renderHome)();
  bindCommon();
  ({home:bindHome,teams:bindTeams,newGame:bindNewGame,game:bindGame,stats:bindStats,data:bindData}[route]||(()=>{}))();
}
function bindCommon(){ $$('[data-route]').forEach(b=>b.onclick=()=>setRoute(b.dataset.route)); }

function renderHome(){
  const completed=state.games.filter(g=>g.status==='completed'); const week=currentWeek(); const weekGames=completed.filter(g=>g.weekId===week?.id);
  const recent=[...completed].sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt))).slice(0,5);
  const live=activeGame();
  return `<section class="hero"><div class="hero-main"><div><p class="eyebrow">REFEREE DESK</p><h1>Sigma Chi<br>Die League</h1></div><button class="btn primary" id="startGame">Start game →</button></div><div class="resume-card card">${live?`<div><p class="eyebrow">IN PROGRESS</p><h2>${esc(live.teamA.name)} vs ${esc(live.teamB.name)}</h2><p class="muted">${live.score.a}–${live.score.b} · ${live.events.length} events</p></div><button class="btn dark" id="resumeGame">Resume</button>`:`<div><p class="eyebrow">STATUS</p><h2>No active game</h2></div><button class="btn" id="startGameSecondary">Start game</button>`}</div></section>
  <section class="metric-grid"><div class="metric card"><span>Active teams</span><strong>${activeTeams().length}</strong></div><div class="metric card"><span>${esc(week?.name||'Current week')} games</span><strong>${weekGames.length}</strong></div><div class="metric card"><span>Season games</span><strong>${completed.length}</strong></div><div class="metric card"><span>Weeks</span><strong>${state.weeks.length}</strong></div></section>
  <section class="two-col"><div class="section-card card"><div class="section-head"><h2>Recent games</h2><button class="btn" data-route="stats">All stats</button></div>${recent.length?`<div class="list">${recent.map(g=>`<div class="list-row"><span class="team-dot" style="background:${g.teamA.color}"></span><div class="list-main"><b>${esc(g.teamA.name)} vs ${esc(g.teamB.name)}</b><span>Game ${g.gameNumber||1} · ${fmtDate(g.date)} · ${esc(state.weeks.find(w=>w.id===g.weekId)?.name||'Unassigned')}</span></div><span class="score-chip">${g.score.a}–${g.score.b}</span></div>`).join('')}</div>`:`<div class="empty">No completed games</div>`}</div><div class="section-card card"><div class="section-head"><h2>Manage</h2></div><div class="list"><button class="list-row btn" data-route="teams"><div class="list-main"><b>Teams</b></div>→</button><button class="list-row btn" data-route="data"><div class="list-main"><b>Weekly merge</b></div>→</button></div></div></section>`;
}
function bindHome(){
  const start=()=>{ if(activeGame()) return toast('Finish or resume the active game first.'); if(activeTeams().length<2){toast('Add at least two teams first.');setRoute('teams');return;} setup={step:1,teamAId:null,teamBId:null,weekId:currentWeek()?.id};setRoute('newGame'); }; $('#startGame')?.addEventListener('click',start); $('#startGameSecondary')?.addEventListener('click',start);
  $('#resumeGame')?.addEventListener('click',()=>setRoute('game'));
}

function renderTeams(){
  return `<div class="page-head"><div><p class="eyebrow">ROSTERS</p><h1 class="page-title">Teams & players</h1></div><div class="actions"><button class="btn" id="addWeek">+ Add week</button><button class="btn" id="addPlayer">+ Add player</button><button class="btn primary" id="addTeam">+ Add team</button></div></div>
  ${state.weeks.length?`<div class="notice">Current reporting period: <b>${esc(currentWeek().name)}</b> · ${fmtDate(currentWeek().startDate)}${currentWeek().endDate?`–${fmtDate(currentWeek().endDate)}`:''}</div>`:''}
  <div class="team-grid">${state.teams.map(t=>`<article class="team-card card" style="--team-color:${t.color}"><p class="eyebrow">${t.active===false?'INACTIVE':'ACTIVE TEAM'}</p><h3>${esc(t.name)}</h3><p class="muted small">${t.players.map(p=>esc(p.name)).join(' · ')}</p><div class="record">${teamRecord(t.id).wins}–${teamRecord(t.id).losses}</div><span class="small muted">Season record</span><footer><button class="btn edit-team" data-id="${t.id}">Edit</button><button class="btn danger toggle-team" data-id="${t.id}">${t.active===false?'Activate':'Deactivate'}</button></footer></article>`).join('')}</div>${state.teams.length?'':'<div class="empty">No teams</div>'}<section class="section-card card" style="margin-top:16px"><div class="section-head"><h2>Player pool</h2><span class="small muted">${state.players.length} players</span></div>${state.players.length?`<div class="list">${state.players.map(p=>{const assigned=state.teams.find(t=>t.players.some(tp=>tp.id===p.id));return `<div class="list-row"><div class="list-main"><b>${esc(p.name)}</b><span>${assigned?esc(assigned.name):'Unassigned'}</span></div><button class="btn edit-player" data-id="${p.id}">Edit</button></div>`;}).join('')}</div>`:'<div class="empty">Add players before creating teams</div>'}</section>`;
}
function bindTeams(){
  $('#addTeam').onclick=()=>openTeamModal(); $('#addPlayer').onclick=()=>openPlayerModal(); $$('.edit-player').forEach(b=>b.onclick=()=>openPlayerModal(state.players.find(p=>p.id===b.dataset.id))); $$('.edit-team').forEach(b=>b.onclick=()=>openTeamModal(team(b.dataset.id))); $$('.toggle-team').forEach(b=>b.onclick=()=>{const t=team(b.dataset.id);t.active=t.active===false?true:false;save();render();}); $('#addWeek').onclick=openWeekModal;
}
function openPlayerModal(existing){
  openModal(`<h2>${existing?'Edit':'Add'} player</h2><label>Player name<input name="name" required value="${esc(existing?.name||'')}"></label><div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" value="default">Save player</button></div>`,form=>{const name=new FormData(form).get('name')?.trim();if(!name)return false;const duplicate=state.players.find(p=>p.id!==existing?.id&&normalize(p.name)===normalize(name));if(duplicate){toast('That player already exists.');return false;}if(existing){existing.name=name;state.teams.forEach(t=>t.players.forEach(p=>{if(p.id===existing.id)p.name=name;}));}else state.players.push({id:uid(),name});save();render();toast('Player saved.');return true;});
}
function openTeamModal(existing){
  const editing=!!existing,assigned=new Set(state.teams.filter(t=>t.id!==existing?.id).flatMap(t=>t.players.map(p=>p.id))),available=state.players.filter(p=>!assigned.has(p.id));
  if(available.length<2){openModal(`<h2>Two players required</h2><p class="muted">Add at least two unassigned players before creating a team.</p><div class="modal-actions"><button class="btn primary" value="cancel">Close</button></div>`,()=>true);return;}
  const options=selected=>`<option value="">Select player</option>${available.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}`;
  openModal(`<h2>${editing?'Edit':'Create'} team</h2><div class="form-grid"><label class="full">Team name<input name="name" required value="${esc(existing?.name||'')}"></label><label>Player 1<select name="p1" required>${options(existing?.players[0]?.id)}</select></label><label>Player 2<select name="p2" required>${options(existing?.players[1]?.id)}</select></label><label class="full">Team color<input name="color" type="color" value="${existing?.color||COLORS[state.teams.length%COLORS.length]}"></label></div><div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="saveModal" value="default">Save team</button></div>`, form=>{
    const fd=new FormData(form),name=fd.get('name')?.trim(),p1=fd.get('p1'),p2=fd.get('p2');if(!name||!p1||!p2)return false;if(p1===p2){toast('Select two different players.');return false;}if(state.teams.some(t=>t.id!==existing?.id&&normalize(t.name)===normalize(name))){toast('That team already exists.');return false;}const players=[p1,p2].map(id=>state.players.find(p=>p.id===id)).filter(Boolean).map(p=>({...p}));if(players.length!==2)return false;
    if(existing){existing.name=name;existing.color=fd.get('color');existing.players=players;}
    else state.teams.push({id:uid(),name,color:fd.get('color'),active:true,players});
    save();render();toast('Team saved.'); return true;
  });
}
function openWeekModal(){
  openModal(`<h2>Add league week</h2><div class="form-grid"><label class="full">Week name<input name="name" required value="Week ${state.weeks.length+1}"></label><label>Start date<input name="start" type="date" required value="${today()}"></label><label>End date<input name="end" type="date"></label></div><div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="saveModal" value="default">Create week</button></div>`,form=>{const fd=new FormData(form);state.weeks.push({id:uid(),number:state.weeks.length+1,name:fd.get('name').trim(),startDate:fd.get('start'),endDate:fd.get('end')});save();render();toast('New week created.');return true;});
}

function renderNewGame(){
  if(!setup) setup={step:1,teamAId:null,teamBId:null,weekId:currentWeek()?.id};
  if(setup.step===1) return `<div class="setup-steps"><span class="active"></span><span></span><span></span></div><div class="page-head"><div><p class="eyebrow">NEW SERIES · SETUP 1 OF 3</p><h1 class="page-title">Choose teams</h1></div><button class="btn" id="quickTeam">+ Create team</button></div><div class="select-team">${activeTeams().map(t=>`<button class="team-option ${setup.teamAId===t.id||setup.teamBId===t.id?'selected':''}" data-team="${t.id}"><span class="team-dot" style="background:${t.color}"></span><b>${esc(t.name)}</b><span>${t.players.map(p=>esc(p.name)).join(' & ')}</span><span>${setup.teamAId===t.id?'TEAM A':setup.teamBId===t.id?'TEAM B':'Select'}</span></button>`).join('')}</div><div class="form-actions"><button class="btn" data-route="home">Cancel</button><button class="btn primary" id="nextSetup" ${setup.teamAId&&setup.teamBId?'':'disabled'}>Set order →</button></div>`;
  const a=team(setup.teamAId),b=team(setup.teamBId);
  if(setup.step===2) return `<div class="setup-steps"><span class="active"></span><span class="active"></span><span></span></div><div class="form-card card"><p class="eyebrow">NEW SERIES · SETUP 2 OF 3</p><h1>Set the throwing order</h1><p class="subtitle">Teams alternate throws. Players rotate within their team in this order.</p><div class="form-grid"><label>League week<select id="weekId">${state.weeks.map(w=>`<option value="${w.id}" ${setup.weekId===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><label>Game 1 starting team<select id="startingTeam"><option value="a">${esc(a.name)}</option><option value="b">${esc(b.name)}</option></select></label><label>${esc(a.name)} first thrower<select id="aFirst"><option value="0">${esc(a.players[0].name)}</option><option value="1">${esc(a.players[1].name)}</option></select></label><label>${esc(b.name)} first thrower<select id="bFirst"><option value="0">${esc(b.players[0].name)}</option><option value="1">${esc(b.players[1].name)}</option></select></label><label class="full">Referee name<input id="refName" value="${esc(state.settings.refereeName||'')}"></label></div><div class="form-actions"><button class="btn" id="backSetup">Back</button><button class="btn primary" id="reviewSetup">Review series →</button></div></div>`;
  const firstTeam=setup.startingTeam==='a'?a:b; const firstIndex=setup.startingTeam==='a'?setup.aFirst:setup.bFirst;
  return `<div class="setup-steps"><span class="active"></span><span class="active"></span><span class="active"></span></div><div class="form-card card"><p class="eyebrow">NEW SERIES · 3 GAMES</p><h1>Ready for Game 1?</h1><div class="metric-grid"><div class="metric card"><span>Team A</span><strong style="font-size:20px">${esc(a.name)}</strong></div><div class="metric card"><span>Team B</span><strong style="font-size:20px">${esc(b.name)}</strong></div><div class="metric card"><span>Starts</span><strong style="font-size:20px">${esc(firstTeam.name)}</strong></div><div class="metric card"><span>First thrower</span><strong style="font-size:20px">${esc(firstTeam.players[firstIndex].name)}</strong></div></div><p class="notice">All three games are played. The first team to two wins takes the series.</p><div class="form-actions"><button class="btn" id="backSetup">Back</button><button class="btn primary" id="beginGame">Start series</button></div></div>`;
}
function bindNewGame(){
  if(setup.step===1){ $$('.team-option').forEach(b=>b.onclick=()=>{const id=b.dataset.team;if(setup.teamAId===id)setup.teamAId=null;else if(setup.teamBId===id)setup.teamBId=null;else if(!setup.teamAId)setup.teamAId=id;else setup.teamBId=id;render();}); $('#nextSetup').onclick=()=>{setup.step=2;render();}; $('#quickTeam').onclick=()=>openTeamModal(); }
  else if(setup.step===2){ $('#backSetup').onclick=()=>{setup.step=1;render();}; $('#reviewSetup').onclick=()=>{setup.weekId=$('#weekId').value;setup.startingTeam=$('#startingTeam').value;setup.aFirst=Number($('#aFirst').value);setup.bFirst=Number($('#bFirst').value);setup.refereeName=$('#refName').value.trim();state.settings.refereeName=setup.refereeName;setup.step=3;save();render();}; }
  else { $('#backSetup').onclick=()=>{setup.step=2;render();}; $('#beginGame').onclick=createGame; }
}
function createGame(){
  const a=structuredClone(team(setup.teamAId)),b=structuredClone(team(setup.teamBId)); const aOrder=setup.aFirst?[a.players[1],a.players[0]]:a.players; const bOrder=setup.bFirst?[b.players[1],b.players[0]]:b.players;
  const s={id:uid(),weekId:setup.weekId,status:'in_progress',teamA:{id:a.id,name:a.name,color:a.color,players:aOrder},teamB:{id:b.id,name:b.name,color:b.color,players:bOrder},initialStartingTeam:setup.startingTeam,refereeName:setup.refereeName||'',gameIds:[],winnerId:null,startedAt:new Date().toISOString(),completedAt:null};
  state.series.push(s);createSeriesGame(s,1);save();setup=null;setRoute('game');
}
function createSeriesGame(s,gameNumber,selectedStarter=null){const startingTeam=selectedStarter||s.initialStartingTeam,g={id:uid(),seriesId:s.id,gameNumber,weekId:s.weekId,date:today(),status:'in_progress',refereeName:s.refereeName,teamA:structuredClone(s.teamA),teamB:structuredClone(s.teamB),startingTeam,turn:{team:startingTeam,indices:{a:0,b:0},number:1},score:{a:0,b:0},events:[],startedAt:new Date().toISOString(),completedAt:null,winnerId:null};state.games.push(g);s.gameIds.push(g.id);state.activeGameId=g.id;return g;}
function seriesForGame(g){return state.series.find(s=>s.id===g?.seriesId);}
function seriesScore(s){const score={a:0,b:0};if(!s)return score;s.gameIds.map(game).filter(g=>g?.status==='completed').forEach(g=>{if(g.winnerId===g.teamA.id)score.a++;if(g.winnerId===g.teamB.id)score.b++;});return score;}

const THROW_BUTTONS=[['table_hit','Table hit','Catch or no catch'],['table_miss','Table miss','0 points'],['sink','Sink','3 points'],['bounce_sink','Bounce sink','3 points'],['rim_hit','Rim hit','1–2 points'],['rim_sink','Rim one → sink other','5 points'],['social','Social','0 points'],['line_foul','Line foul','0 points'],['ceiling_foul','Ceiling foul','0 points'],['self_sink','Self sink','3 to opponents']];
function renderGame(){
  const g=activeGame(); if(!g)return `<div class="empty">No game is currently in progress.<br><br><button class="btn" data-route="home">Return home</button></div>`;
  const side=g.turn.team,t=side==='a'?g.teamA:g.teamB,p=t.players[g.turn.indices[side]%2],s=seriesForGame(g),ss=seriesScore(s);
  return `<div class="game-shell"><div class="live-top"><div><span class="live-pill">● GAME ${g.gameNumber||1} OF 3</span><p class="small muted">Series ${ss.a}–${ss.b} · ${esc(state.weeks.find(w=>w.id===g.weekId)?.name||'Week')} · ${esc(g.refereeName||'No referee')}</p></div><button class="btn danger" id="finishGame">End game</button></div><section class="scoreboard card"><div class="score-team"><small>TEAM A · SERIES ${ss.a}</small><h2>${esc(g.teamA.name)}</h2><div class="score">${g.score.a}</div></div><div class="score-mid">FIRST TO 11<br>WIN BY 2<strong>${g.turn.number}</strong>THROW</div><div class="score-team right"><small>SERIES ${ss.b} · TEAM B</small><h2>${esc(g.teamB.name)}</h2><div class="score">${g.score.b}</div></div></section><section class="turn-banner card" style="--turn-color:${t.color}"><div><p class="eyebrow">THROWER</p><h3>${esc(p.name)} · ${esc(t.name)}</h3></div><span class="small muted">Next: ${esc((side==='a'?g.teamB:g.teamA).players[g.turn.indices[side==='a'?'b':'a']%2].name)}</span></section><section class="section-card card"><div class="section-head"><h2>Throw result</h2></div><div class="event-grid">${THROW_BUTTONS.map(([id,name,note])=>`<button class="event-btn throw-type" data-type="${id}">${name}<small>${note}</small></button>`).join('')}<button class="event-btn penalty" id="knockover">Mug knocked over<small>+3 per mug to selected team</small></button></div></section><div class="game-controls"><button class="btn" id="undoEvent" ${g.events.length?'':'disabled'}>↶ Undo</button><button class="btn" id="pauseGame">Exit game</button></div><section class="event-log section-card card"><div class="section-head"><h2>Game log</h2><span class="small muted">${g.events.length} events</span></div>${g.events.length?[...g.events].reverse().map((e,i)=>eventRow(e,g.events.length-i,g)).join(''):'<div class="empty">No events</div>'}</section></div>`;
}
function eventRow(e,num,g){const pts=`${e.points.a?`${g.teamA.name} +${e.points.a}`:''}${e.points.a&&e.points.b?' · ':''}${e.points.b?`${g.teamB.name} +${e.points.b}`:''}`||'0 points';return `<div class="event-row"><span class="rank">${num}</span><div><b>${esc(e.label)}</b><div class="small muted">${esc(e.playerName||e.actor||'Referee event')}${e.catchLabel?` · ${esc(e.catchLabel)}`:''}</div></div><span class="event-points ${e.points.a||e.points.b?'positive':''}">${esc(pts)}</span></div>`;}
function bindGame(){
  $$('.throw-type').forEach(b=>b.onclick=()=>openThrowModal(b.dataset.type)); $('#knockover').onclick=openKnockoverModal; $('#undoEvent').onclick=undoEvent; $('#pauseGame').onclick=()=>setRoute('home'); $('#finishGame').onclick=finishGame;
}
function throwContext(){const g=activeGame(),side=g.turn.team,t=side==='a'?g.teamA:g.teamB,p=t.players[g.turn.indices[side]%2],opp=side==='a'?g.teamB:g.teamA;return{g,side,t,p,opp};}
function openThrowModal(type){
  const {p,opp}=throwContext(); const label=THROW_BUTTONS.find(x=>x[0]===type)?.[1]||type;
  let body='';
  const playerOptions=opp.players.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
  const catchFields=`<div id="caughtFields" hidden><label>Catching player<select name="catcher"><option value="">Select player</option>${playerOptions}</select></label></div><div id="missedFields" class="form-grid" hidden><label>First missed catcher<select name="missed1"><option value="">Select player</option>${playerOptions}</select></label><label>Second missed catcher<select name="missed2"><option value="">None</option>${playerOptions}</select></label></div>`;
  if(type==='table_hit') body=`<label>Catch result<select name="result" id="catchResult"><option value="uncaught">No catch attempted / fell off (1 point)</option><option value="caught">Caught (0 points)</option><option value="missed">Catch attempted and missed (1 point)</option><option value="stayed">Landed and stayed — Social (0 points)</option></select></label>${catchFields}`;
  if(type==='rim_hit') body=`<label>Rim outcome<select name="result" id="catchResult"><option value="fell">Fell off — no catch attempted (2 points)</option><option value="fell_missed">Catch attempted and missed — fell off (2 points)</option><option value="caught">Caught (1 point)</option><option value="stayed">Landed and stayed (1 point)</option></select></label>${catchFields}`;
  if(type==='sink'||type==='bounce_sink'||type==='rim_sink') body=`<label>Sunk mug<select name="target">${opp.players.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>${type==='rim_sink'?'<p class="notice warning">Use this only when the die rims one mug and sinks the other. If it rims and sinks the same mug, record a normal Sink for 3 points.</p>':''}`;
  if(type==='self_sink') body=`<label>Sunk mug<select name="target">${throwContext().t.players.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>`;
  openModal(`<h2>${esc(label)}</h2><p class="muted">Throw by ${esc(p.name)}</p>${body}<div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="saveModal" value="default">Record throw</button></div>`,form=>{const data=new FormData(form),result=data.get('result'),catcher=data.get('catcher'),missed1=data.get('missed1'),missed2=data.get('missed2');if(result==='caught'&&!catcher){toast('Select the player who made the catch.');return false;}if((result==='missed'||result==='fell_missed')&&!missed1){toast('Select at least one player who missed the catch.');return false;}if(missed1&&missed1===missed2){toast('Select two different players.');return false;}recordThrow(type,data);return true;});
  const resultSelect=$('#catchResult');
  if(resultSelect){const sync=()=>{const result=resultSelect.value;$('#caughtFields').hidden=result!=='caught';$('#missedFields').hidden=!(result==='missed'||result==='fell_missed');};resultSelect.addEventListener('change',sync);sync();}
}
function recordThrow(type,fd){
  const {g,side,p,opp}=throwContext(); let a=0,b=0,catchStatus='not_available',catcherId=null,catcherIds=[],catchLabel='',modifiers=[],targetPlayerId=fd.get('target')||null,label=THROW_BUTTONS.find(x=>x[0]===type)?.[1]||type;
  const award=(to,points)=>{if(to==='a')a+=points;else b+=points;};
  if(type==='table_hit'){const result=fd.get('result');if(result==='caught'){catcherId=fd.get('catcher');catcherIds=[catcherId];catchStatus='caught';catchLabel=`Caught by ${playerName(opp,catcherId)}`;}else if(result==='missed'){catcherIds=[fd.get('missed1'),fd.get('missed2')].filter(Boolean);catchStatus='missed';catchLabel=`Missed by ${catcherIds.map(id=>playerName(opp,id)).join(' & ')}`;award(side,1);}else if(result==='stayed'){type='social';label='Social';catchStatus='no_attempt';}else{catchStatus='no_attempt';award(side,1);}}
  else if(type==='rim_hit'){const result=fd.get('result');if(result==='caught'){catcherId=fd.get('catcher');catcherIds=[catcherId];catchStatus='caught';catchLabel=`Caught by ${playerName(opp,catcherId)}`;award(side,1);}else if(result==='fell_missed'){catcherIds=[fd.get('missed1'),fd.get('missed2')].filter(Boolean);catchStatus='missed';catchLabel=`Missed by ${catcherIds.map(id=>playerName(opp,id)).join(' & ')}`;award(side,2);}else if(result==='stayed'){catchStatus='no_attempt';catchLabel='Stayed on table';award(side,1);}else{catchStatus='no_attempt';catchLabel='Fell off table';award(side,2);}}
  else if(type==='sink'){award(side,3);}else if(type==='bounce_sink'){award(side,3);modifiers.push('bounce');}else if(type==='rim_sink'){award(side,5);modifiers.push('rim');}else if(type==='self_sink'){award(side==='a'?'b':'a',3);}else if(type==='social'||type==='table_miss'||type==='line_foul'||type==='ceiling_foul'){}
  const e={id:uid(),kind:'throw',sequence:g.events.length+1,turnNumber:g.turn.number,teamSide:side,teamId:side==='a'?g.teamA.id:g.teamB.id,throwerId:p.id,playerName:p.name,type,label,modifiers,catchStatus,catcherId,catcherIds,catchLabel,targetPlayerId,points:{a,b},scoreBefore:{...g.score},createdAt:new Date().toISOString()};
  g.score.a+=a;g.score.b+=b;e.scoreAfter={...g.score};g.events.push(e);g.turn.indices[side]=(g.turn.indices[side]+1)%2;g.turn.team=side==='a'?'b':'a';g.turn.number++;save();render();checkGameOver(g);
}
function playerName(teamSnapshot,id){return teamSnapshot.players.find(p=>p.id===id)?.name||'Unknown player';}
function openKnockoverModal(){const {g}=throwContext();openModal(`<h2>Mug knocked over</h2><p class="muted">The referee chooses which team receives 3 points per mug. No player is charged with the event.</p><div class="form-grid"><label>Points awarded to<select name="award"><option value="a">${esc(g.teamA.name)}</option><option value="b">${esc(g.teamB.name)}</option></select></label><label>Number of mugs<input name="count" type="number" min="1" max="10" value="1"></label></div><div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="saveModal" value="default">Award points</button></div>`,form=>{const fd=new FormData(form),award=fd.get('award'),count=Math.max(1,Number(fd.get('count'))||1),a=award==='a'?count*3:0,b=award==='b'?count*3:0,awardedTeam=award==='a'?g.teamA:g.teamB;g.events.push({id:uid(),kind:'penalty',sequence:g.events.length+1,label:`Mug knocked over · ${count*3} points awarded`,actor:`Awarded to ${awardedTeam.name}`,awardedTeam:award,count,points:{a,b},scoreBefore:{...g.score},createdAt:new Date().toISOString()});g.score.a+=a;g.score.b+=b;g.events.at(-1).scoreAfter={...g.score};save();render();checkGameOver(g);return true;});}
function undoEvent(){const g=activeGame(),e=g.events.pop();if(!e)return;g.score={...e.scoreBefore};if(e.kind==='throw'){g.turn.team=e.teamSide;g.turn.indices[e.teamSide]=(g.turn.indices[e.teamSide]+1)%2;g.turn.number=Math.max(1,g.turn.number-1);}save();render();toast('Last event undone.');}
function winningSide(g){if(Math.max(g.score.a,g.score.b)<11||Math.abs(g.score.a-g.score.b)<2)return null;return g.score.a>g.score.b?'a':'b';}
function checkGameOver(g){if(winningSide(g))setTimeout(()=>{if(activeGame()?.id===g.id)finishGame(true);},0);}
function finishGame(automatic=false){const g=activeGame(),side=winningSide(g);if(!side){openModal(`<h2>Game is not over</h2><p class="muted">A team must reach 11 and lead by 2.</p><div class="modal-actions"><button class="btn primary" value="cancel">Continue</button></div>`,()=>true);return;}const winner=side==='a'?g.teamA:g.teamB,s=seriesForGame(g),hasNext=s&&(g.gameNumber||1)<3,nextNumber=(g.gameNumber||1)+1,nextStarter=hasNext?`<label>Game ${nextNumber} starting team<select name="nextStarter" required><option value="">Select team</option><option value="a">${esc(g.teamA.name)}</option><option value="b">${esc(g.teamB.name)}</option></select></label>`:'';openModal(`<p class="eyebrow">${automatic?'GAME OVER':'FINAL SCORE'}</p><h2>${esc(winner.name)} wins Game ${g.gameNumber||1}</h2><p class="muted">${esc(g.teamA.name)} ${g.score.a}–${g.score.b} ${esc(g.teamB.name)}</p>${nextStarter}<div class="modal-actions"><button class="btn" value="undo" formnovalidate>Undo last event</button><button class="btn primary" id="saveModal" value="default">${hasNext?`Start Game ${nextNumber}`:'Complete series'}</button></div>`,(form,button)=>{if(button?.value==='undo'){undoEvent();return true;}const selectedStarter=hasNext?new FormData(form).get('nextStarter'):null;if(hasNext&&!selectedStarter){toast('Select the starting team.');return false;}g.status='completed';g.completedAt=new Date().toISOString();g.winnerId=winner.id;if(hasNext){createSeriesGame(s,nextNumber,selectedStarter);save();setRoute('game');toast(`Game ${g.gameNumber} completed.`);return true;}if(s){const final=seriesScore(s);s.status='completed';s.completedAt=new Date().toISOString();s.winnerId=final.a>final.b?s.teamA.id:s.teamB.id;}state.activeGameId=null;save();setRoute('stats');toast('Series completed.');return true;});}

function completedGames(scope=selectedWeek){const completed=state.games.filter(g=>g.status==='completed');if(scope==='all')return completed;if(scope.startsWith('game:'))return completed.filter(g=>g.id===scope.slice(5));return completed.filter(g=>g.weekId===scope);}
function teamRecord(teamId,games=completedGames('all'),scope='all'){let wins=0,losses=0,ties=0,pf=0,pa=0;const relevant=games.filter(g=>g.teamA.id===teamId||g.teamB.id===teamId),groups=new Map();relevant.forEach(g=>{const key=g.seriesId||g.id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(g);});groups.forEach(group=>{const s=group[0].seriesId?state.series.find(x=>x.id===group[0].seriesId):null;if(!scope.startsWith('game:')&&s&&s.status!=='completed')return;group.forEach(g=>{const isA=g.teamA.id===teamId;pf+=isA?g.score.a:g.score.b;pa+=isA?g.score.b:g.score.a;});if(scope.startsWith('game:')){const g=group[0],isA=g.teamA.id===teamId,x=isA?g.score.a:g.score.b,y=isA?g.score.b:g.score.a;if(x>y)wins++;else if(x<y)losses++;else ties++;return;}if(s){if(s.winnerId===teamId)wins++;else losses++;}else{const g=group[0],isA=g.teamA.id===teamId,x=isA?g.score.a:g.score.b,y=isA?g.score.b:g.score.a;if(x>y)wins++;else if(x<y)losses++;else ties++;}});return{wins,losses,ties,pf,pa,played:wins+losses+ties};}
function playerRows(games){
  const map=new Map();
  const blank=(id,name,teamName)=>({id,name,team:teamName,throws:0,successfulThrows:0,tableHits:0,tableMisses:0,sinks:0,directSinks:0,bounceSinks:0,rimSinks:0,rims:0,socials:0,lineFouls:0,ceilingFouls:0,fouls:0,selfSinks:0,catches:0,missedCatches:0,points:0});
  games.forEach(g=>{
    [g.teamA,g.teamB].forEach(t=>t.players.forEach(p=>{if(!map.has(p.id))map.set(p.id,blank(p.id,p.name,t.name));}));
    g.events.forEach(e=>{
      if(e.kind!=='throw')return;
      const row=map.get(e.throwerId)||blank(e.throwerId,e.playerName,e.teamSide==='a'?g.teamA.name:g.teamB.name);
      row.throws++;
      if(['table_hit','social','sink','bounce_sink','rim_hit','rim_sink'].includes(e.type))row.successfulThrows++;
      if(e.type==='table_hit'||e.type==='social')row.tableHits++;
      if(e.type==='table_miss')row.tableMisses++;
      if(['sink','bounce_sink','rim_sink'].includes(e.type))row.sinks++;
      if(e.type==='sink')row.directSinks++;
      if(e.type==='bounce_sink')row.bounceSinks++;
      if(e.type==='rim_sink')row.rimSinks++;
      if(e.type==='rim_hit'||e.type==='rim_sink'||e.modifiers?.includes('rim'))row.rims++;
      if(e.type==='social')row.socials++;
      if(e.type==='line_foul'){row.lineFouls++;row.fouls++;}
      if(e.type==='ceiling_foul'){row.ceilingFouls++;row.fouls++;}
      if(e.type==='self_sink')row.selfSinks++;
      row.points+=e.points[e.teamSide]||0;
      map.set(row.id,row);
      const catchTeam=e.teamSide==='a'?g.teamB:g.teamA;
      const catcherIds=e.catcherIds?.length?e.catcherIds:(e.catcherId?[e.catcherId]:[]);
      catcherIds.forEach(id=>{const cp=catchTeam.players.find(p=>p.id===id);if(!cp)return;const cr=map.get(cp.id)||blank(cp.id,cp.name,catchTeam.name);if(e.catchStatus==='caught')cr.catches++;if(e.catchStatus==='missed')cr.missedCatches++;map.set(cp.id,cr);});
    });
  });
  return [...map.values()];
}
function renderStats(){
  const games=completedGames(); const rows=state.teams.map(t=>({team:t,...teamRecord(t.id,games,selectedWeek)})).sort((a,b)=>b.wins-a.wins||(b.pf-b.pa)-(a.pf-a.pa)); const players=playerRows(games);
  const gameOptions=[...state.games].filter(g=>g.status==='completed').reverse().map(g=>`<option value="game:${g.id}" ${selectedWeek===`game:${g.id}`?'selected':''}>Game ${g.gameNumber||1}: ${esc(g.teamA.name)} ${g.score.a}–${g.score.b} ${esc(g.teamB.name)} · ${fmtDate(g.date)}</option>`).join('');
  return `<div class="page-head"><div><p class="eyebrow">LEAGUE</p><h1 class="page-title">Stats & history</h1></div></div><div class="filter-row"><label>Scope<select id="statsWeek"><option value="all" ${selectedWeek==='all'?'selected':''}>Overall</option><optgroup label="Weeks">${state.weeks.map(w=>`<option value="${w.id}" ${selectedWeek===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</optgroup>${gameOptions?`<optgroup label="Games">${gameOptions}</optgroup>`:''}</select></label></div><div class="tabs"><button class="tab ${statsTab==='teams'?'active':''}" data-tab="teams">Teams</button><button class="tab ${statsTab==='players'?'active':''}" data-tab="players">Players</button><button class="tab ${statsTab==='rankings'?'active':''}" data-tab="rankings">Rankings</button><button class="tab ${statsTab==='games'?'active':''}" data-tab="games">Games</button></div>${statsTab==='teams'?teamStatsTable(rows):statsTab==='players'?playerStatsTable(players):statsTab==='rankings'?rankingsView(players):gameHistory(games)}`;
}
function teamStatsTable(rows){return `<div class="section-card card"><div class="section-head"><h2>Standings</h2><span class="small muted">${rows.length} teams</span></div><div style="overflow:auto"><table class="stats-table"><thead><tr><th>#</th><th>Team</th><th class="num">GP</th><th class="num">W</th><th class="num">L</th><th class="num">PF</th><th class="num">PA</th><th class="num">Diff</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="rank">${i+1}</td><td><b>${esc(r.team.name)}</b><div class="small muted">${r.team.players.map(p=>esc(p.name)).join(' · ')}</div></td><td class="num">${r.played}</td><td class="num">${r.wins}</td><td class="num">${r.losses}</td><td class="num">${r.pf}</td><td class="num">${r.pa}</td><td class="num">${r.pf-r.pa}</td></tr>`).join('')}</tbody></table></div></div>`;}
function playerStatsMarkup(rows){return `<div style="overflow:auto"><table class="stats-table"><thead><tr><th>Player</th><th class="num">Throws</th><th class="num">Table hits</th><th class="num">Table misses</th><th class="num">Sinks</th><th class="num">Direct sinks</th><th class="num">Bounce sinks</th><th class="num">Rim→sink</th><th class="num">Rims</th><th class="num">Socials</th><th class="num">Line fouls</th><th class="num">Ceiling fouls</th><th class="num">Self sinks</th><th class="num">Catches</th><th class="num">Missed catches</th><th class="num">Pts</th></tr></thead><tbody>${rows.sort((a,b)=>b.points-a.points).map(r=>`<tr><td><b>${esc(r.name)}</b><div class="small muted">${esc(r.team)}</div></td><td class="num">${r.throws}</td><td class="num">${r.tableHits}</td><td class="num">${r.tableMisses}</td><td class="num">${r.sinks}</td><td class="num">${r.directSinks}</td><td class="num">${r.bounceSinks}</td><td class="num">${r.rimSinks}</td><td class="num">${r.rims}</td><td class="num">${r.socials}</td><td class="num">${r.lineFouls}</td><td class="num">${r.ceilingFouls}</td><td class="num">${r.selfSinks}</td><td class="num">${r.catches}</td><td class="num">${r.missedCatches}</td><td class="num"><b>${r.points}</b></td></tr>`).join('')}</tbody></table></div>`;}
function playerStatsTable(rows){return `<div class="section-card card"><div class="section-head"><h2>Player statistics</h2><span class="small muted">Every tracked result · scroll horizontally</span></div>${rows.length?playerStatsMarkup(rows):'<div class="empty">No player events in this period.</div>'}</div>`;}
function rankingsView(rows){
  const withValue=(denominator,value)=>rows.filter(denominator).map(r=>({...r,rankValue:value(r)})).sort((a,b)=>b.rankValue-a.rankValue||b.throws-a.throws);
  const percent=value=>`${(value*100).toFixed(1)}%`;
  const boards=[
    {title:'Throw percentage',note:'Successful throws ÷ total throws',rows:withValue(r=>r.throws>0,r=>r.successfulThrows/r.throws),format:percent,detail:r=>`${r.successfulThrows}/${r.throws}`},
    {title:'Sink percentage',note:'Sinks ÷ total throws',rows:withValue(r=>r.throws>0,r=>r.sinks/r.throws),format:percent,detail:r=>`${r.sinks}/${r.throws}`},
    {title:'Catch percentage',note:'Catches ÷ catch attempts',rows:withValue(r=>r.catches+r.missedCatches>0,r=>r.catches/(r.catches+r.missedCatches)),format:percent,detail:r=>`${r.catches}/${r.catches+r.missedCatches}`},
    {title:'Points per throw',note:'Throwing points ÷ total throws',rows:withValue(r=>r.throws>0,r=>r.points/r.throws),format:v=>v.toFixed(2),detail:r=>`${r.points} pts`},
    {title:'Total sinks',note:'All sink types',rows:withValue(r=>r.sinks>0,r=>r.sinks),format:v=>String(v),detail:r=>`${r.throws} throws`},
    {title:'Total catches',note:'Completed catches',rows:withValue(r=>r.catches>0,r=>r.catches),format:v=>String(v),detail:r=>`${r.catches+r.missedCatches} attempts`}
  ];
  return `<div class="ranking-grid">${boards.map(rankingCard).join('')}</div>`;
}
function rankingCard(board){return `<section class="section-card card"><div class="section-head"><div><h2>${board.title}</h2><span class="small muted">${board.note}</span></div></div>${board.rows.length?`<div class="list">${board.rows.slice(0,5).map((r,i)=>`<div class="list-row"><span class="ranking-place">${i+1}</span><div class="list-main"><b>${esc(r.name)}</b><span>${esc(r.team)} · ${board.detail(r)}</span></div><strong class="ranking-value">${board.format(r.rankValue)}</strong></div>`).join('')}</div>`:'<div class="empty">No qualifying attempts</div>'}</section>`;}
function gameHistory(games){return `<div class="section-card card"><div class="section-head"><h2>Completed games</h2><span class="small muted">${games.length} games</span></div>${games.length?`<div class="list">${[...games].reverse().map(g=>`<div class="list-row"><div class="list-main"><b>${esc(g.teamA.name)} vs ${esc(g.teamB.name)}</b><span>Game ${g.gameNumber||1} of 3 · ${fmtDate(g.date)} · ${esc(g.refereeName||'Unknown ref')} · ${g.events.length} events</span></div><span class="score-chip">${g.score.a}–${g.score.b}</span><button class="btn game-detail" data-id="${g.id}">Details</button></div>`).join('')}</div>`:'<div class="empty">No completed games in this period.</div>'}</div>`;}
function bindStats(){ $$('.tab').forEach(b=>b.onclick=()=>{statsTab=b.dataset.tab;render();}); $('#statsWeek').onchange=e=>{selectedWeek=e.target.value;render();}; $$('.game-detail').forEach(b=>b.onclick=()=>openGameDetails(game(b.dataset.id))); }
function openGameDetails(g){
  const rows=playerRows([g]);
  openModal(`<p class="eyebrow">GAME ${g.gameNumber||1} OF 3</p><h2>${esc(g.teamA.name)} ${g.score.a}–${g.score.b} ${esc(g.teamB.name)}</h2><p class="muted">${fmtDate(g.date)} · Ref: ${esc(g.refereeName||'Unknown')}</p><h3>Complete player breakdown</h3>${playerStatsMarkup(rows)}<h3>Event log</h3><div class="event-log">${g.events.map((e,i)=>eventRow(e,i+1,g)).join('')}</div><div class="modal-actions"><button class="btn primary" value="cancel">Close</button></div>`,()=>true,true);
}

function renderData(){const week=currentWeek();return `<div class="page-head"><div><p class="eyebrow">WEEKLY SYNC</p><h1 class="page-title">Merge referee data</h1><p class="subtitle">Every referee can export their games. Import all files on one device to create the combined week.</p></div></div><div class="two-col"><section class="section-card card"><div class="section-head"><h2>1. Export</h2></div><p class="muted">Choose a week and download its teams, games, events, and referee details as one JSON file.</p><label>Week<select id="exportWeek">${state.weeks.map(w=>`<option value="${w.id}" ${w.id===week?.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><br><button class="btn primary" id="exportData">Download week file</button></section><section class="section-card card"><div class="section-head"><h2>2. Import & merge</h2></div><div class="merge-zone"><h3>Bring the refs together</h3><p class="muted">Select one or several exported JSON files. Existing game IDs are skipped, so files are safe to import twice.</p><button class="btn dark" id="chooseImport">Choose referee files</button></div></section></div><section class="section-card card" style="margin-top:18px"><div class="section-head"><h2>How the merge works</h2></div><div class="list"><div class="list-row"><span class="rank">01</span><div class="list-main"><b>Share the same roster first</b><span>Export a week/roster file and let each referee import it before games begin.</span></div></div><div class="list-row"><span class="rank">02</span><div class="list-main"><b>Refs work independently</b><span>Every game autosaves locally on that referee’s device.</span></div></div><div class="list-row"><span class="rank">03</span><div class="list-main"><b>Export after the games</b><span>Each referee sends the commissioner their weekly file.</span></div></div><div class="list-row"><span class="rank">04</span><div class="list-main"><b>Import every file</b><span>Teams are matched, player IDs are reconciled, and duplicate games are ignored.</span></div></div></div></section><section class="section-card card" style="margin-top:18px"><div class="section-head"><div><p class="eyebrow">DEBUG</p><h2>Local data</h2></div><button class="btn danger" id="clearLocalData">Clear all local data</button></div><p class="small muted">Removes teams, players, weeks, games, and settings saved in this browser.</p></section>`;}
function bindData(){ $('#exportData').onclick=()=>exportWeek($('#exportWeek').value); $('#chooseImport').onclick=()=>$('#importFile').click(); $('#clearLocalData').onclick=confirmClearLocalData; }
function confirmClearLocalData(){openModal(`<p class="eyebrow">DEBUG RESET</p><h2>Clear all local data?</h2><p class="muted">This permanently removes this browser’s teams, players, weeks, games, and settings. Exported files are not affected.</p><div class="modal-actions"><button class="btn" value="cancel">Cancel</button><button class="btn danger" value="clear">Clear everything</button></div>`,(form,button)=>{if(button?.value!=='clear')return false;localStorage.removeItem(STORAGE_KEY);state=initialState();route='home';selectedWeek='all';statsTab='teams';setup=null;save();render();toast('Local data cleared.');return true;});}
function exportWeek(weekId){const w=state.weeks.find(x=>x.id===weekId);const data={format:FORMAT,exportedAt:new Date().toISOString(),league:state.league,week:w,players:state.players,teams:state.teams,series:state.series.filter(s=>s.weekId===weekId),games:state.games.filter(g=>g.weekId===weekId)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`die-${(w?.name||'week').replace(/\s+/g,'-').toLowerCase()}-${today()}.json`;a.click();URL.revokeObjectURL(url);toast('Week file downloaded.');}
async function importFiles(files){let added=0,skipped=0;for(const file of files){let data;try{data=JSON.parse(await file.text());}catch{toast(`${file.name} is not valid JSON.`);continue;}if(data.format!==FORMAT||!data.week||!Array.isArray(data.games)||!Array.isArray(data.teams)){toast(`${file.name} is not a Die week file.`);continue;}const weekMap=mergeWeek(data.week),maps=mergeTeams(data.teams,data.players||[]);for(const raw of data.series||[]){const incoming=structuredClone(raw);incoming.weekId=weekMap;remapSeries(incoming,maps);const existing=state.series.find(s=>s.id===incoming.id);if(existing){existing.gameIds=[...new Set([...(existing.gameIds||[]),...(incoming.gameIds||[])])];if(incoming.status==='completed'){existing.status='completed';existing.completedAt=incoming.completedAt;existing.winnerId=incoming.winnerId;}}else state.series.push(incoming);}for(const raw of data.games){if(state.games.some(g=>g.id===raw.id)){skipped++;continue;}const g=structuredClone(raw);g.weekId=weekMap;remapGame(g,maps);state.games.push(g);added++;}}save();render();toast(`Merged ${added} game${added===1?'':'s'}; skipped ${skipped} duplicate${skipped===1?'':'s'}.`);}
function mergeWeek(incoming){let w=state.weeks.find(x=>x.id===incoming.id)||state.weeks.find(x=>x.number===incoming.number&&normalize(x.name)===normalize(incoming.name));if(!w){w=structuredClone(incoming);state.weeks.push(w);}return w.id;}
function mergeTeams(incoming,incomingPlayers=[]){const teamIds=new Map(),playerIds=new Map(),pool=[...incomingPlayers,...incoming.flatMap(t=>t.players||[])];pool.forEach(ip=>{if(playerIds.has(ip.id))return;let lp=state.players.find(p=>p.id===ip.id)||state.players.find(p=>normalize(p.name)===normalize(ip.name));if(!lp){lp={id:ip.id||uid(),name:ip.name};state.players.push(lp);}playerIds.set(ip.id,lp.id);});incoming.forEach(it=>{let local=state.teams.find(t=>t.id===it.id)||state.teams.find(t=>normalize(t.name)===normalize(it.name));if(!local){local={...structuredClone(it),players:(it.players||[]).map(ip=>{const id=playerIds.get(ip.id)||ip.id,player=state.players.find(p=>p.id===id);return{id,name:player?.name||ip.name};})};state.teams.push(local);}teamIds.set(it.id,local.id);});return{teamIds,playerIds};}
function remapSeries(s,maps){['teamA','teamB'].forEach(key=>{s[key].id=maps.teamIds.get(s[key].id)||s[key].id;s[key].players.forEach(p=>p.id=maps.playerIds.get(p.id)||p.id);});if(s.winnerId)s.winnerId=maps.teamIds.get(s.winnerId)||s.winnerId;}
function remapGame(g,maps){['teamA','teamB'].forEach(key=>{g[key].id=maps.teamIds.get(g[key].id)||g[key].id;g[key].players.forEach(p=>p.id=maps.playerIds.get(p.id)||p.id);});if(g.winnerId)g.winnerId=maps.teamIds.get(g.winnerId)||g.winnerId;g.events.forEach(e=>{e.teamId=maps.teamIds.get(e.teamId)||e.teamId;e.throwerId=maps.playerIds.get(e.throwerId)||e.throwerId;e.catcherId=maps.playerIds.get(e.catcherId)||e.catcherId;if(Array.isArray(e.catcherIds))e.catcherIds=e.catcherIds.map(id=>maps.playerIds.get(id)||id);e.targetPlayerId=maps.playerIds.get(e.targetPlayerId)||e.targetPlayerId;});}

function openModal(html,onSave,wide=false){const d=$('#modal'),form=$('#modalForm');d.classList.toggle('wide',wide);$('#modalContent').innerHTML=html;form.onsubmit=e=>{if(e.submitter?.value==='cancel')return; e.preventDefault(); if(onSave(form,e.submitter)!==false)d.close();};d.showModal();}
$('#importFile').addEventListener('change',e=>{if(e.target.files.length)importFiles([...e.target.files]);e.target.value='';});
$$('.app-header [data-route]').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));
render();
